x = 15
y = 7
sum = x+y
print("addition =", sum)
subtraction = x-y
print("subtraction=", subtraction)
multiplication = x+y
print("multiplication=", multiplication)
division = x/y
print("division=", division)
